### ISSUE TITLE
Release as a module project on drupal.org

### ISSUE THREAD

**Issue by ajitdev** [michaelrobbe/commerce_discount_first_time_customer#1]
Kudos for the module!
I had the exact same implementation in mind before coming up to your module.
I just wanted to know if you are planning to release it as a project on drupal.org? Or if you do not mind I can do it adding you as a maintainer (I have "vetted" user access for creating full projects). I might make a few changes (coding standards, renaming, or functional etc.).
Please let me know how can we collaborate.

**Comment by michaelrobbe** [comment]
I hadn't planned on releasing it, but if you feel like it would benefit the community, absolutely, by all means. I'm open to your review/vet, and being added as a maintainer.

**Comment by ajitdev** [comment]
Thanks for the prompt response! I will work on testing the module and will make any changes required.
I will push the code (with all the older commits) to a sandbox project and promote to full project when I test it completely.
Can you please let me know your drupal.org username so that I could add you as a maintainer?

**Comment by michaelrobbe** [comment]
My Drupal.org username is "michaelrobbe"

**Comment by ajitdev** [comment]
Looks like you already have created a sandbox project on your drupal.org account. Listing of options that I could think of so that we could promote this module to a full project:
1.  [Apply for permission to create full projects](https://www.drupal.org/node/1011698) - This is done ideally after checking the [Project application checklist](https://www.drupal.org/node/1587704). From the initial review I am not sure if this could be a valid option because the number of lines in the module are less. Also, this process takes long time to complete ([Module Approval Process is Too Slow](https://groups.drupal.org/node/139754)).
2. [Single project promotion](https://www.drupal.org/node/2505727) - This is done when your code is not big enough to get you the "vetted" access. This again has to go through the review process as in step 1.
3. Transfer the ownership to a user who has access to promote the project - ([Example of the transfer ownership](https://www.drupal.org/node/1857056)) : In this case either you would have to create an issue similar to the one in example or I can do it and you can comment on it giving your approval. One cannot simply promote sandbox project created by other user (I might loose on the my "vetted" user access I do so.

I am proposing these solutions in spirit of [collaboration over competition](https://www.drupal.org/contribute/development#collaboration). Please let me know which of these option would you prefer. I would be glad to help in any of the option.

**Comment by ajitdev** [comment]
I talked to "Klausi" - git administrator on drupal.org and he said it is okay if I publish the module if I am the maintainer. In that way the ownership of the module could stay with you, we could publish the module, and create new releases. Win win :)
Could you please add me as a maintainer to the sandbox project? My drupal.org username is **AjitS** (username search on the maintainers tab is case sensitive).

**Comment by ajitdev** [comment]
I have created a issue (https://www.drupal.org/node/2659996) in the module's issue queue for offering my help to maintain the module and to help planning the stable release.
Could you please take a look?

**Comment by ajitdev** [comment]
Thanks a ton. I got the access alright. I have created a separate issue because I am not able to promote. Have moved the same issue to the webmasters issue queue.
Thanks for your support! Closing this issue.
